plugin.MULTIPLE_CHOICE=co.edu.unicauca.bancopreguntas.plugins.MultipleChoiceQuestionPlugin
plugin.CASE_BASED=co.edu.unicauca.bancopreguntas.plugins.CaseBasedQuestionPlugin
plugin.MULTIMEDIA=co.edu.unicauca.bancopreguntas.plugins.MultimediaQuestionPlugin
plugin.EXCEL_IMPORT=co.edu.unicauca.bancopreguntas.plugins.ExcelImportQuestionPlugin
plugin.AI_GENERATOR=co.edu.unicauca.bancopreguntas.plugins.AIGeneratorQuestionPlugin
